spring.application.name=kripta

# ===============================
# = ??????????? ? ???? ??????
# ===============================
# spring.datasource.url=jdbc:postgresql://localhost:5432/kripta_db
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/kripta_db}
# spring.datasource.username=kripta_user
spring.datasource.username=${DB_USERNAME:kripta_user}
# spring.datasource.password=kripta_password
spring.datasource.password=${DB_PASSWORD:kripta_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = ????????? JPA (HIBERNATE)
# ===============================
# ?????????????? ????????/?????????? ????? ??
# validate - ?????? ????????? ???????????? ????????? ? ?????? (??? ?????????)
# update - ????????? ????? (??????? ??????????? ???????/???????, ?? ?? ???????)
# create-drop - ??????? ??? ?????? ? ??????? ??? ????????? (?????? ??? ??????)
# none - ?????? ?? ??????
spring.jpa.hibernate.ddl-auto=validate

# ?????????? SQL-??????? ? ??????? (??????? ??? ???????)
spring.jpa.show-sql=false

# ????????????? SQL ??? ??????????
spring.jpa.properties.hibernate.format_sql=true

# ??????? PostgreSQL (????? ?? ?????????, Spring Boot ????????? ?????????????)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# = ???? ??????????? ???????
# ===============================
server.address=0.0.0.0
# server.port=25565
server.port=${PORT:25565}

openrouter.api.key=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

# ===============================
# = ??????????? (???????????)
# ===============================
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE