spring.application.name=kripta

# ===============================
# = ??????????? ? ???? ??????
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/kripta_db
spring.datasource.username=kripta_user
spring.datasource.password=kripta_password
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = ????????? JPA (HIBERNATE)
# ===============================
# ?????????????? ????????/?????????? ????? ??
# validate - ?????? ????????? ???????????? ????????? ? ?????? (??? ?????????)
# update - ????????? ????? (??????? ??????????? ???????/???????, ?? ?? ???????)
# create-drop - ??????? ??? ?????? ? ??????? ??? ????????? (?????? ??? ??????)
# none - ?????? ?? ??????
spring.jpa.hibernate.ddl-auto=validate

# ?????????? SQL-??????? ? ??????? (??????? ??? ???????)
spring.jpa.show-sql=false

# ????????????? SQL ??? ??????????
spring.jpa.properties.hibernate.format_sql=true

# ??????? PostgreSQL (????? ?? ?????????, Spring Boot ????????? ?????????????)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# = ???? ??????????? ???????
# ===============================
server.address=0.0.0.0
server.port=25565

# ===============================
# = ??????????? (???????????)
# ===============================
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE