CREATE TABLE IF NOT EXISTS coin (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    symbol VARCHAR NOT NULL UNIQUE,
    coingecko_id VARCHAR UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS metrics (
    id BIGSERIAL PRIMARY KEY,
    coin_id BIGINT NOT NULL REFERENCES coin(id) ON DELETE CASCADE,
    price DECIMAL(20,8) NOT NULL,
    market_cap DECIMAL(20,2) NOT NULL,
    volume_24h DECIMAL(20,2) NOT NULL,
    unix_seconds BIGINT NOT NULL,
    fetched_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO coin (name, symbol, coingecko_id) VALUES
    ('Bitcoin', 'BTC', 'bitcoin'),
    ('Etherium', 'ETH', 'ethereum'),
    ('Tether', 'USDT', 'tether'),
    ('XRP', 'XRP', 'ripple'),
    ('BNB', 'BNB', 'binancecoin'),
    ('USDC', 'USDC', 'usd-coin'),
    ('Solana', 'SOL', 'solana'),
    ('TRON', 'TRX', 'tron'),
    ('Figure Heloc', 'FIGR_HELOC', 'figure-heloc'),
    ('Dogecoin', 'DOGE', 'dogecoin'),
    ('WhiteBIT Coin', 'WBT', 'whitebit'),
    ('USDS', 'USDS', 'usds'),
    ('Bitcoin Cash', 'BCH', 'bitcoin-cash'),
    ('Cardano', 'ADA', 'cardano'),
    ('LEO Token', 'LEO', 'leo-token'),
    ('Hyperliquid', 'HYPE', 'hyperliquid'),
    ('Ethena USDe', 'USDE', 'ethena-usde'),
    ('Canton', 'CC', 'canton-network'),
    ('Monero', 'XMR', 'monero'),
    ('Chainlink', 'LINK', 'chainlink'),
    ('Stellar', 'XLM', 'stellar'),
    ('USD1', 'USD1', 'usd1'),
    ('Rain', 'RAIN', 'rain'),
    ('Dai', 'DAI', 'dai'),
    ('PayPal USD', 'PYUSD', 'paypal-usd'),
    ('Hedera', 'HBAR', 'hedera-hashgraph'),
    ('Litecoin', 'LTC', 'litecoin'),
    ('Zcash', 'ZEC', 'zcash'),
    ('Avalanche', 'AVAX', 'avalanche-2'),
    ('Shiba Inu', 'SHIB', 'shiba-inu'),
    ('Sui', 'SUI', 'sui'),
    ('Toncoin', 'TON', 'the-open-network'),
    ('Cronos', 'CRO', 'crypto-com-chain'),
    ('World Liberty Financial', 'WLFI', 'world-liberty-financial'),
    ('Tether Gold', 'XAUT', 'tether-gold'),
    ('MemeCore', 'M', 'memecore'),
    ('PAX Gold', 'PAXG', 'pax-gold'),
    ('Uniswap', 'UNI', 'uniswap'),
    ('Polkadot', 'DOT', 'polkadot'),
    ('BlackRock USD Institutional Digital Liquidity Fund', 'BUIDL', 'buidl'),
    ('Mantle', 'MNT', 'mantle'),
    ('Falcon USD', 'USDF', 'falcon-finance'),
    ('Aave', 'AAVE', 'aave'),
    ('Aster', 'ASTER', 'aster-2'),
    ('Global Dollar', 'USDG', 'global-dollar'),
    ('Pepe', 'PEPE', 'pepe'),
    ('Circle USYC', 'USYC', 'hashnote-usyc'),
    ('Bittensor', 'TAO', 'bittensor'),
    ('Ripple USD', 'RLUSD', 'ripple-usd'),
    ('Bitget Token', 'BGB', 'bitget-token')
ON CONFLICT (symbol) DO NOTHING;